### ISSUE TITLE
Select Freehand annotation tool, try to move the dots, they do not stick with the line

### ISSUE THREAD

**Issue by ManojSolanki** [ivmartel/dwv-angular#29]
If i select the Freehand annotation tool, then try to move the dots, they do not stick with the line. Can you please update DWV node module with fixing this issue.

Thanks in Advance

**Comment by ivmartel** [comment]
This is fixed in dwv 0.23.6 that will be integrated in #28.

**Comment by ManojSolanki** [comment]
Hi Ivmartel,

I have just updated my dwv to version 0.23.6 but this issue not resolved, i have attached a short video to to demonstrate the issue.

Please have a look. 
https://goo.gl/BwnH97

**Comment by ivmartel** [comment]
It works in the dwv-jqmobile [trunk demo](https://ivmartel.github.io/dwv-jqmobile/demo/trunk/index.html). Are you sure you are using the latest (dwvs' title in your video shows v0.23.3)?

**Comment by ivmartel** [comment]
I guess closing means you were not using the latest...
